apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes: # Define volume
        - name: shared
          persistentVolumeClaim:
            claimName: file-share
      containers:
        - name: todo-app-fe
          image: dubeaka/todo-app:3.0
          volumeMounts:
            - name: shared
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "8081"
        - name: todo-app-be
          image: dubeaka/todo-app-backend:2.0
          volumeMounts:
            - name: shared
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "8082"